apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: chaos-testing
spec:
  interval: 5m
  chart:
    spec:
      chart: chaos-mesh
      version: '2.6.3'
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
  # Use valuesFrom to source large or environment-specific values from a
  # ConfigMap stored in the repository. This keeps the HelmRelease small and
  # allows Flux to render the chart with the provided values.yaml content.
  valuesFrom:
    - kind: ConfigMap
      name: chaos-mesh-values
      valuesKey: values.yaml