apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 5m
  path: "gitops/ingress-nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system