apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda-scaledobjects
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 5m
  path: "gitops/keda-scaledobjects"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: keda