apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-certificates
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 5m
  dependsOn:
    - name: cert-manager
  path: "gitops/linkerd-certificates"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager