apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 5m
  path: "gitops/monitoring"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Health checks for monitoring components
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-operator
      namespace: monitoring