apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx