apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Separate Flux Kustomizations with proper dependency chains
# FluxInstance is applied separately during setup
resources:
  #  Deploy Flux Kustomizations with dependency chain:
  - gitops/kustomizations/