apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
  - grafana.127.0.0.1.nip.io
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
