apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: "k8s-dev-local-ca"
  secretName: "ca-key-pair"
  duration: 87600h # 10 years
  privateKey:
    algorithm: RSA
    size: 4096
  subject:
    organizations:
    - "Dev Local CA"
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
