apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-workloads
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - app-backend
      - app-frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s