apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '57.0.2'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      # Enable default dashboards
      defaultDashboardsEnabled: true
    # Disable problematic ServiceMonitors for Kind
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    # Keep working components
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    coreDns:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus:
      prometheusSpec:
        retention: 30d
        # Enable service discovery for custom ServiceMonitors
        serviceMonitorSelectorNilUsesHelmValues: false