---
# Install only Linkerd-specific CRDs using kubectl apply
# This avoids the Gateway API CRDs conflict with Traefik
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-policy-crds-script
  namespace: linkerd
data:
  install-crds.sh: |
    #!/bin/bash
    set -e
    
    # Install Linkerd policy CRDs directly from the Linkerd releases
    LINKERD_VERSION="stable-2.14.10"
    
    echo "Installing Linkerd policy CRDs..."
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_authorizationpolicies.yaml
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_httproutes.yaml
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_meshtlsauthentications.yaml
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_networkauthentications.yaml
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_serverauthorizations.yaml
    kubectl apply -f https://raw.githubusercontent.com/linkerd/linkerd2/${LINKERD_VERSION}/policy-controller/k8s/crds/policy.linkerd.io_servers.yaml
    
    echo "Linkerd policy CRDs installed successfully!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: linkerd-policy-crds-installer
  namespace: linkerd
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: linkerd-policy-crds-installer
      restartPolicy: OnFailure
      containers:
      - name: installer
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "/scripts/install-crds.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
      volumes:
      - name: script
        configMap:
          name: linkerd-policy-crds-script
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-policy-crds-installer
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-policy-crds-installer
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-policy-crds-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-policy-crds-installer
subjects:
- kind: ServiceAccount
  name: linkerd-policy-crds-installer
  namespace: linkerd
