apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 5m
  dependsOn:
    - name: linkerd-crds
      namespace: linkerd
  chart:
    spec:
      chart: linkerd-viz
      version: 30.12.11
      sourceRef:
        kind: HelmRepository
        name: linkerd-stable
        namespace: flux-system
  values:
    # Enable the Linkerd dashboard
    dashboard:
      enabled: true
    web:
      # allow local.test (include port suffix in regexp)
      enforcedHostRegexp: '^(localhost|127\.0\.0\.1|local\.test|web\.linkerd-viz\.svc\.cluster\.local)(:\d+)?$'