apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-crds
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: linkerd-stable
        namespace: flux-system
  values:
    installGatewayAPI: true