apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
  annotations:
    # Reloader will watch these ConfigMaps and Secrets and restart Linkerd pods when they change
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: "linkerd-identity-trust-roots"
    secret.reloader.stakater.com/reload: "linkerd-identity-issuer"
spec:
  interval: 5m
  timeout: 15m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: linkerd-crds
      namespace: linkerd
  chart:
    spec:
      chart: linkerd-control-plane
      version: 1.16.11
      sourceRef:
        kind: HelmRepository
        name: linkerd-stable
        namespace: flux-system
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls