apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 1m
  chart:
    spec:
      chart: keda
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  values:
    # default values; you can adjust operator and metrics server settings
    metricsServer:
      enabled: true
