apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaledobject-chaos
  namespace: app-backend
spec:
  scaleTargetRef:
    name: backend
  minReplicaCount: 2
  maxReplicaCount: 3
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
      # Trigger on node CPU usage (fraction 0..1). This query returns average
      # node CPU usage across instances using node_exporter metrics.
      # KEDA will activate when this value > threshold (0.5 = 50%).
      query: 'avg(1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])))'
      threshold: '0.1'
    # No authenticationRef required for in-cluster Prometheus
