apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos-daemon
  namespace: chaos-testing
spec:
  template:
    spec:
      containers:
      - name: chaos-daemon
        command:
        - /usr/local/bin/chaos-daemon
        - --runtime
        - containerd
        - --http-port
        - "31766"
        - --grpc-port
        - "31767"
        - --pprof
        - --ca
        - /etc/chaos-daemon/cert/ca.crt
        - --cert
        - /etc/chaos-daemon/cert/tls.crt
        - --key
        - /etc/chaos-daemon/cert/tls.key
        - --runtime-socket-path
        - /host-run/containerd.sock
      volumes:
      - name: socket-path
        hostPath:
          path: /run/k3s/containerd
          type: DirectoryOrCreate
